### PR TITLE
Dark mode

### PR DESCRIPTION
**Pull request by Mxchaeltrxn**
I've made the dark mode changes.

It feels a bit repetitive having to redeclare the selectors but I can't think of another way.

I also realised that we'll have to change the favicon if we tone down the pink in the header logo, which I'll need your help with.

Also, I'm not sure how changing the background colour of the logo in dark mode affects the brand (since there are now two colours) but I think that's okay. 

No screenshots because it's probably easier to have a look on the deployed pages.

### CODE REVIEW

**Comment by haydn** [comment]
@Mxchaeltrxn Thanks for picking this up!

> It feels a bit repetitive having to redeclare the selectors but I can't think of another way.

An option is to use CSS variables:

https://developer.mozilla.org/en-US/docs/Web/CSS/Using_CSS_custom_properties

Here's a simplified example:

```css
:root {
  --bg-color: red;
}

@media (prefers-color-scheme: dark) {
  :root {
    --bg-color: blue;
  }
}

body {
  background: var(--bg-color);
}
```

> I also realised that we'll have to change the favicon if we tone down the pink in the header logo, which I'll need your help with.
>
> Also, I'm not sure how changing the background colour of the logo in dark mode affects the brand (since there are now two colours) but I think that's okay.

Let's leave the background and favicon with `#f0f` for now. In fact, let's leave the whole header background `#f0f`. I've been meaning to take a look at #8 (I'm keen to keep that hot pink and instead work out a way to have less of it on screen so it's a little less intense), but let's get this one merged with the current header first.

I don't think lightening the header text in dark mode is a good idea either:

image

image

That [contrast ratio](https://webaim.org/articles/contrast/) on the tagline is way too low:

image

So for now, let's not change the header at all in dark mode.

**Comment by Mxchaeltrxn** [comment]
@haydn Thanks for that. I've changed the colours back but after reading your comment on contrast, I'm not so sure about the `pre` blocks and how to colour them. 

Concretely, the `pre` block background colour doesn't contrast well with the background colour of the page. I tried a few different types (shades?) of pink for the text with black-ish and grey-ish backgrounds but none of them had sufficient contrast. (note: I'm just using the same gradient as in light mode now).

The good thing is that the text has enough contrast with the background though.

image

**Comment by haydn** [comment]
The background of the `pre` code blocks doesn't need to contrast strongly with the page background, what's important is that the text contrasts with the background so that it is legible. Which, looks good as it is. 👍 

I noticed heading and tagline in the header is still changing to white in dark mode:

image

Let's just make those black in dark mode — exactly matching light mode so the contrast of the tagline isn't an issue.

**Comment by Mxchaeltrxn** [comment]
@haydn Yep I must've missed that. Done!

**Pull request merged**
